version: '3'

services:
  database:
    image: websublime/postgres
    container_name: "gotrue_database"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ${DATA_PATH}/database:/var/lib/postgresql/data
      - ${PWD}/migrations/postgres:/docker-entrypoint-initdb.d/
